## 4장 보강자료

간단한 데이터로 살펴보는 Backpropagation 예시 및 실습

In [2]:
import numpy as np

# 1. 데이터 및 변수 초기화
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # XOR 연산의 입력 값
y = np.array([[0], [1], [1], [0]])             # XOR 연산의 결과 값

# 가중치와 바이어스 초기화
np.random.seed(42)

필요한 함수들을 정의합니다:

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def mse_loss(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

### 모델 구조

1-레이어이고, input 변수가 2개인 신경망을 사용해서 backpropagation을 구현해봅시다.  
히든레이어의 뉴런의 수는 2개 입니다.

### Forward Pass


$$
z_1 = XW_1 + b_1
$$
$$
a_1 = \sigma(z_1)
$$
$$
L = \frac{1}{m} \sum_{i=1}^{m} (y_i - a1_i)^2
$$

### Backward Pass

$$
\frac{\partial L}{\partial a1} = (a1 - y)
$$
$$
\frac{\partial L}{\partial z1} = \frac{\partial L}{\partial a1} \times \sigma'(a_1)
$$
$$
\frac{\partial L}{\partial W1} = X^T \frac{\partial L}{\partial z1}
$$
$$
\frac{\partial L}{\partial b1} = \sum \frac{\partial L}{\partial z1}
$$

### Weight Update:

$$
W_1 = W_1 - \text{learning\_rate} \times \frac{\partial L}{\partial W1}
$$
$$
b_1 = b_1 - \text{learning\_rate} \times \frac{\partial L}{\partial b1}
$$


### 코드 구현

In [4]:
input_size = 2
output_size = 1

W1 = np.random.randn(input_size, output_size)
b1 = np.zeros((1, output_size))

learning_rate = 0.1
epochs = 10000

# 3. 학습 시작
for epoch in range(epochs):
    # Forward Pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    # 4. 손실 계산
    loss = np.mean((y - a1) ** 2)

    # 5. Backward Pass
    da1 = (a1 - y)
    dz1 = da1 * sigmoid_derivative(a1)
    dW1 = np.dot(X.T, dz1)
    db1 = np.sum(dz1, axis=0, keepdims=True)

    # 6. 가중치 업데이트
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    # 일정 에포크마다 손실 출력
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}/{epochs}, Loss: {loss:.4f}")

# 최종 예측 출력
print("Predicted Output:")
print(a1)

Epoch 0/10000, Loss: 0.2563
Epoch 1000/10000, Loss: 0.2500
Epoch 2000/10000, Loss: 0.2500
Epoch 3000/10000, Loss: 0.2500
Epoch 4000/10000, Loss: 0.2500
Epoch 5000/10000, Loss: 0.2500
Epoch 6000/10000, Loss: 0.2500
Epoch 7000/10000, Loss: 0.2500
Epoch 8000/10000, Loss: 0.2500
Epoch 9000/10000, Loss: 0.2500
Predicted Output:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


네, 간단한 2-레이어 신경망을 사용하여 backpropagation을 구현함. 

이 예제에서는:

1. 입력 레이어와 2개의 숨겨진 레이어를 가진 신경망을 구축합니다.
2. 시그모이드를 활성화 함수로 사용합니다.
3. 평균 제곱 오차를 손실 함수로 사용합니다.

필요한 라이브러리 임포트

### Neural Network Model:

#### 1. Forward Pass:
1. **Hidden Layer**:
    - $$ z_1 = X \times W_1 + b_1 $$
    - $$ a_1 = \sigma(z_1) $$

2. **Output Layer**:
    - $$ z_2 = a_1 \times W_2 + b_2 $$
    - $$ a_2 = \sigma(z_2) $$

여기서,   $ \sigma $ 는 sigmoid 활성화 함수를 의미합니다.

#### 2. Loss Function:
- $$ L = \frac{1}{N} \sum_{i=1}^{N} (y_i - a_{2,i})^2 $$

여기서, $ N $ 은 데이터의 개수를 의미합니다.

#### 3. Backward Pass (Gradients):

- **Output Layer**:
    - $$ \frac{\partial L}{\partial a_2} = 2(a_2 - y) $$
    - $$ \frac{\partial L}{\partial z_2} = \frac{\partial L}{\partial a_2} \times \sigma'(z_2) $$
    - $$ \frac{\partial L}{\partial W_2} = a_1^T \times \frac{\partial L}{\partial z_2} $$
    - $$ \frac{\partial L}{\partial b_2} = \sum_{i=1}^{N} \frac{\partial L}{\partial z_{2,i}} $$

- **Hidden Layer**:
    - $$ \frac{\partial L}{\partial a_1} = \frac{\partial L}{\partial z_2} \times W_2^T $$
    - $$ \frac{\partial L}{\partial z_1} = \frac{\partial L}{\partial a_1} \times \sigma'(z_1) $$
    - $$ \frac{\partial L}{\partial W_1} = X^T \times \frac{\partial L}{\partial z_1} $$
    - $$ \frac{\partial L}{\partial b_1} = \sum_{i=1}^{N} \frac{\partial L}{\partial z_{1,i}} $$


In [5]:
import numpy as np

이제 2-레이어 신경망의 파라미터를 초기화하겠습니다:

In [6]:
input_size = 2
hidden_size = 3
output_size = 1

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

In [7]:
W1

array([[ 0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473]])

이제 실제로 forward pass 및 backpropagation을 실행할 학습 코드를 작성하겠습니다:

In [8]:
learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    # Forward Pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # 손실 계산
    loss = np.mean((y - a2) ** 2)

    # Backward Pass
    da2 = (a2 - y)
    dz2 = da2 * sigmoid_derivative(a2)
    dW2 = np.dot(a1.T, dz2)
    db2 = np.sum(dz2, axis=0, keepdims=True)

    da1 = np.dot(dz2, W2.T)
    dz1 = da1 * sigmoid_derivative(a1)
    dW1 = np.dot(X.T, dz1)
    db1 = np.sum(dz1, axis=0, keepdims=True)

    # 가중치 업데이트
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    # 일정 에포크마다 손실 출력
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}/{epochs}, Loss: {loss:.4f}")

# 최종 예측 출력
print("Predicted Output:")
print(a2)

Epoch 0/10000, Loss: 0.2440
Epoch 1000/10000, Loss: 0.1881
Epoch 2000/10000, Loss: 0.0920
Epoch 3000/10000, Loss: 0.0313
Epoch 4000/10000, Loss: 0.0149
Epoch 5000/10000, Loss: 0.0092
Epoch 6000/10000, Loss: 0.0065
Epoch 7000/10000, Loss: 0.0049
Epoch 8000/10000, Loss: 0.0040
Epoch 9000/10000, Loss: 0.0033
Predicted Output:
[[0.02224667]
 [0.94486905]
 [0.94514992]
 [0.06836053]]


### Homework

히든 레이어의 수가 2개이고, 각 레이어의 뉴런의 수가 3개인 뉴럴네트워크를 같은 형태로 구현해봅시다

In [28]:
import numpy as np

def min_max_scaling(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))

A = np.array([10, 20, 30, 40, 50])
B = np.array([500, 600, 700, 800, 900])

A_scaled = min_max_scaling(A)
B_scaled = min_max_scaling(B)

print("Scaled A:", A_scaled)
print("Scaled B:", B_scaled)

Scaled A: [0.   0.25 0.5  0.75 1.  ]
Scaled B: [0.   0.25 0.5  0.75 1.  ]


In [31]:
import numpy as np

def standardization(data):
    return (data - np.mean(data)) / np.std(data)

A = np.array([10, 20, 30, 40, 50])
B = np.array([500, 600, 700, 760, 850])

A_standard = standardization(A)
B_standard = standardization(B)

print("Standardized A:", A_standard)
print("Standardized B:", B_standard)


Standardized A: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Standardized B: [-1.49120227 -0.67186036  0.14748154  0.63908669  1.3764944 ]
